#!/bin/bash

CHROME_VERSION=$(/opt/google/chrome/chrome -version | awk '{ print $3 }')

cat <<_EOF
{
  "capabilities": [
    {
      "version": ${CHROME_VERSION},
      "browserName": "chrome",
      "maxInstances": $NODE_MAX_INSTANCES,
      "seleniumProtocol": "WebDriver",
      "instanceId": "${INSTANCE_ID}",
      "applicationName": "$NODE_APPLICATION_NAME"
    }
  ],
  "custom": {
            "uuid":"$UUID",
            "instanceId": "$INSTANCE_ID",
            "createdDate":"$CREATED_DATE",
            "createdBrowser":"$CREATED_BROWSER",
            "createdOs":"$CREATED_OS"
        },
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": $NODE_MAX_SESSION,
  "port": $NODE_PORT,
  "register": true,
  "registerCycle": $NODE_REGISTER_CYCLE,
  "nodePolling": $NODE_POLLING,
  "unregisterIfStillDownAfter": $NODE_UNREGISTER_IF_STILL_DOWN_AFTER,
  "downPollingLimit": $NODE_DOWN_POLLING_LIMIT,
  "timeout": 600,
  "browserTimeout":600
}
_EOF
